import {
  Component,
  OnInit
} from '@angular/core';

import { CommonModule } from '@angular/common';

import {
  ActivatedRoute,
  RouterModule
} from '@angular/router';

import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

import {
  faCalendar,
  faClock,
  faTag,
  faArrowLeft,
  faShareNodes
} from '@fortawesome/free-solid-svg-icons';

import {
  faTwitter,
  faLinkedin,
  faFacebook
} from '@fortawesome/free-brands-svg-icons';

import { Article } from '../../models/article.model';

import {
  Meta,
  Title,
  DomSanitizer,
  SafeHtml
} from '@angular/platform-browser';

import { Header } from '../../components/header/header';

import {
  ArticlesService
} from '../../services/articles-service';

import {
  MarkdownConverterService
} from '../../services/markdown-converter-service';

import {
  LanguageService
} from '../../services/language-service';

import {
  TranslateModule,
  TranslateService
} from '@ngx-translate/core';

import { firstValueFrom } from 'rxjs';

import mermaid from 'mermaid';

import { MermaidStyleService } from './mermaid-style-service';
import { MERMAID_CONFIG } from './mermaid-theme';



@Component({
  selector: 'app-article',

  imports: [
    CommonModule,
    RouterModule,
    FontAwesomeModule,
    Header,
    TranslateModule
  ],

  templateUrl: './article.html',
})
export class ArticleComponent implements OnInit {

  faCalendar = faCalendar;
  faClock = faClock;
  faTag = faTag;
  faArrowLeft = faArrowLeft;
  faShareNodes = faShareNodes;

  faTwitter = faTwitter;
  faLinkedin = faLinkedin;
  faFacebook = faFacebook;


  article?: Article;

  content: SafeHtml = '';

  loading: boolean = true;

  showShareMenu: boolean = false;


  constructor(
    private activatedRoute: ActivatedRoute,

    private articlesService: ArticlesService,

    private markdownConverter: MarkdownConverterService,

    private translateService: TranslateService,

    private languageService: LanguageService,

    private meta: Meta,

    private title: Title,

    private sanitizer: DomSanitizer,
    private mermaidStyle: MermaidStyleService
  ) {

    /*
     * Initialize Mermaid before any diagram
     * rendering takes place.
     */
    mermaid.initialize(MERMAID_CONFIG);
  }


  ngOnInit(): void {

    this.activatedRoute.params.subscribe(
      params => {

        const articleId =
          params['articleId'];

        this.loadArticle(articleId);
      }
    );
  }


  loadArticle(id: string): void {

    this.loading = true;

    this.articlesService
      .getArticleById(id)
      .subscribe({

        next: (article) => {

          if (!article) {

            this.loading = false;

            return;
          }

          this.article = article;

          this.updateMetaTags();

          this.loadContent(article.file);
        },


        error: (error) => {

          console.error(
            'Failed to load article:',
            error
          );

          this.loading = false;
        }
      });
  }


  loadContent(filename: string): void {

    this.articlesService
      .getArticleContent(filename)
      .subscribe({

        next: (content) => {

          this.convertMarkdownToHtml(content);
        },


        error: (error) => {

          console.error(
            'Failed to load article content:',
            error
          );

          this.loading = false;
        }
      });
  }


  async convertMarkdownToHtml(
    md: string
  ): Promise<void> {

    try {

      /*
       * 1. Convert Markdown to HTML
       */
      const html =
        await firstValueFrom(
          this.markdownConverter
            .convertMarkdownToHtml(md)
        );


      /*
       * 2. Convert GitHub Mermaid
       *    blocks into language-mermaid blocks
       */
      const contentWithMermaid =
        this.markdownConverter
          .processMermaidBlocks(html);


      console.log(
        'HTML after Mermaid processing:',
        contentWithMermaid
      );


      /*
       * 3. Render Mermaid diagrams
       */
      const renderedContent =
        await this.renderMermaidDiagrams(
          contentWithMermaid
        );


      console.log(
        'Final rendered HTML:',
        renderedContent
      );


      /*
       * 4. Tell Angular that this HTML has
       *    already been processed.
       *
       * IMPORTANT:
       * Only do this after the content has
       * been processed/generated by us.
       */
      this.content =
        this.sanitizer
          .bypassSecurityTrustHtml(
            renderedContent
          );


      this.loading = false;

    } catch (error) {

      console.error(
        'Failed to process Markdown content:',
        error
      );

      this.loading = false;
    }
  }


  private async renderMermaidDiagrams(
    content: string
  ): Promise<string> {

    /*
     * Create a temporary DOM container.
     *
     * We manipulate the HTML here before
     * giving it to Angular.
     */
    const container =
      document.createElement('div');

    container.innerHTML = content;


    /*
     * Find all Mermaid code blocks.
     */
    const mermaidBlocks =
      container.querySelectorAll(
        'code.language-mermaid'
      );


    console.log(
      `Found ${mermaidBlocks.length} Mermaid diagram(s)`
    );


    /*
     * Render each Mermaid diagram.
     */
    for (
      let i = 0;
      i < mermaidBlocks.length;
      i++
    ) {

      const codeElement =
        mermaidBlocks[i];


      /*
       * Extract Mermaid source code.
       */
      const mermaidCode =
        codeElement.textContent?.trim();


      if (!mermaidCode) {

        console.warn(
          `Mermaid block ${i + 1} is empty`
        );

        continue;
      }


      try {

        let id: string;

        try {

          /*
           * Mermaid requires a unique ID
           * for every rendered diagram.
           */
          id =
            `mermaid-${crypto.randomUUID()}`;
        } catch (error) {

          /*
           * Do not use crypto.randomUUID().
           *
           * It is not supported in some mobile
           * browsers / WebViews.
           */
          id =
            `mermaid-${Date.now()}-${i}-${Math.random()
              .toString(36)
              .substring(2, 9)}`;
        }


        /*
         * Generate the SVG.
         */
        const { svg } =
          await mermaid.render(
            id,
            mermaidCode
          );


        console.log(
          `Generated SVG for Mermaid diagram ${i + 1}`
        );


        /*
         * Find the complete GitHub wrapper:
         *
         * <div class="highlight highlight-source-mermaid">
         *     <pre>
         *         <code class="language-mermaid">
         *             ...
         *         </code>
         *     </pre>
         * </div>
         */
        const wrapper =
          codeElement.closest(
            '.highlight-source-mermaid'
          );


        if (!wrapper) {

          console.warn(
            `No Mermaid wrapper found for diagram ${i + 1}`
          );

          continue;
        }


        /*
         * Create a clean container for
         * the generated SVG.
         */
        const svgContainer =
          document.createElement('div');


        svgContainer.className =
          'mermaid-container';


        /*
         * Put the generated SVG inside it.
         */
        svgContainer.innerHTML = this.mermaidStyle.enhance(svg);


        /*
         * Replace the entire GitHub
         * Mermaid code block.
         *
         * We deliberately remove <pre>
         * because <pre> is meant for
         * preformatted text/code and can
         * interfere with the SVG.
         */
        wrapper.replaceWith(
          svgContainer
        );


        console.log(
          `Successfully rendered Mermaid diagram ${i + 1}`
        );

      } catch (error) {

        console.error(
          `Failed to render Mermaid diagram ${i + 1}:`,
          error
        );
      }
    }


    /*
     * Return the final HTML.
     *
     * At this point the Mermaid source
     * code blocks have been replaced
     * with SVG elements.
     */
    return container.innerHTML;
  }


  updateMetaTags(): void {

    if (!this.article) {
      return;
    }


    this.title.setTitle(
      `${this.article.title} | Blog`
    );


    this.meta.updateTag({
      name: 'description',
      content: this.article.description
    });


    this.meta.updateTag({
      property: 'og:title',
      content: this.article.title
    });


    this.meta.updateTag({
      property: 'og:description',
      content: this.article.description
    });


    if (this.article.coverImage) {

      this.meta.updateTag({
        property: 'og:image',
        content: this.article.coverImage
      });
    }
  }


  formatDate(
    dateString: string
  ): string {

    return this.languageService
      .formatDate(dateString);
  }


  toggleShareMenu(): void {

    this.showShareMenu =
      !this.showShareMenu;
  }


  shareOn(
    platform: string
  ): void {

    const url =
      window.location.href;

    const title =
      this.article?.title || '';

    let shareUrl = '';


    switch (platform) {

      case 'twitter':

        shareUrl =
          `https://twitter.com/intent/tweet?` +
          `url=${encodeURIComponent(url)}` +
          `&text=${encodeURIComponent(title)}`;

        break;


      case 'linkedin':

        shareUrl =
          `https://www.linkedin.com/sharing/share-offsite/?` +
          `url=${encodeURIComponent(url)}`;

        break;


      case 'facebook':

        shareUrl =
          `https://www.facebook.com/sharer/sharer.php?` +
          `u=${encodeURIComponent(url)}`;

        break;
    }


    if (shareUrl) {

      window.open(
        shareUrl,
        '_blank',
        'width=600,height=400'
      );
    }
  }


  copyLink(): void {

    navigator.clipboard
      .writeText(
        window.location.href
      )

      .then(() => {

        alert('Lien copié!');
      })

      .catch(error => {

        console.error(
          'Failed to copy link:',
          error
        );
      });
  }


  get getMadeWithLoveByText(): string {

    const author =
      this.article?.author ||
      this.translateService.instant(
        'HERO.KENNICHE_ABDERRAZAK'
      );


    return this.translateService.instant(
      'OTHERS.BY_ENTITY',
      {
        ENTITY:
          '<span class="text-lime-400 font-semibold">' +
          author +
          '</span>',
      }
    );
  }
}